### ISSUE TITLE
Multiple Google Shopping Feeds

### ISSUE THREAD

**Issue by uncenteredDiv** [fontis/fontis_feedsgenerator#2] opened 2015-06-16 17:08 UTC
Is it possible to create multiple Feeds from the same Catalog?

The second feed would be the exact like the first feed - except for the sku (Prefix + SKU)

My idea was to duplicate the Google Shopping Feed - e.g. Google Shopping 2 / Google Shopping 3

Any ideas?

**Comment by chnorton** [comment] 2015-06-16 23:38
So you want a duplicate of an existing feed, but to have all of the SKUs automatically prefixed with a set string? If you're only looking to prepend something to the SKU field, and otherwise keep the feed the same, I'd recommend just copying the existing feed file and modifying it with a script, rather than attempting to generate a new file from scratch.

**Comment by uncenteredDiv** [comment] 2015-06-21 17:44
That was also my first thought - but than i have to make a new feed each time I upgrade my catalog.
I've made a copy of the existing feed and added the prefix via "Search and Replace".

Maybe you consider this feature on the next update :)

**Closed as completed** 2015-06-21 17:44 UTC
